In [1]:
import pandas as pd
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.support.ui import Select
import time

In [3]:

website = 'https://www.akiyajapan.com/search/list?categories%5B%5D=buy&sizeUnit=sqm&categories%5B%5D=house&order_by=date_desc'
#path = r'D:\programming files\Python\Jupyter\chromedriver-win64\chromedriver.exe' #chrome driver file path
#service = Service(path)
#driver = webdriver.Chrome(service=service)
driver = webdriver.Chrome() 
driver.get(website)

table_view = driver.find_element(By.XPATH, '//*[@id="table-view-btn"]') #this line is about calling button for it to click auto 
table_view.click()


#drop_down = Select(driver.find_element(By.ID, 'country'))
#drop_down.select_by_index(1)

time.sleep(3)

soup = BeautifulSoup(driver.page_source, 'html.parser')

In [4]:
table = soup.find_all('tr')

In [5]:
for match in table:
    tds = match.find_all('td')

    cleaned_cells = []

    for i, td in enumerate(tds):
        # 🖼️ Handle image separately (first column)
        if i == 0:
            img_tag = td.find('img')
            if img_tag:
                image = img_tag.get('src') or img_tag.get('data-src') or ''
            else:
                image = ''
            cleaned_cells.append(image)
        else:
            text = td.text.strip()
            parts = text.split('\n')

            for part in parts:
                if part.strip():
                    cleaned_cells.append(part.strip())

    # Ensure fixed length
    while len(cleaned_cells) < 7:
        cleaned_cells.append('')

    image, location, price, types, beds, house, konbini = cleaned_cells[:7]

    print([image, location, price, types, beds, house, konbini])

['', '', '', '', '', '', '']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_9ad0c743-6783-11f1-bd67-a6ae20f6eefe_85d3f789ee341.jpg', 'Ichigawa, Chiba', 'Apartment, Land · 3 bed', '$170,000', 'Apartment, Land', '3', '-']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_8a7ccfd8-6783-11f1-bd67-a6ae20f6eefe_9e7e9b498ac14.jpg', 'Funabashi, Chiba', 'House · 3 bed', '$180,000', 'House', '3', '96m²']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_68bb6f22-6783-11f1-bd67-a6ae20f6eefe_402b0fd529119.jpg', 'Funabashi, Chiba', 'House · 3 bed', '$180,000', 'House', '3', '128m²']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_5681eb20-6783-11f1-bd67-a6ae20f6eefe_fbf22b9858ae9.jpg', 'Funabashi, Chiba', 'House, Land · 5 bed', '$190,000', 'House, Land', '5', '136m²']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_429f4df0-6783-11f1-bd67-a6ae20f6eefe_6243a911bb850.jpg', 'Funabashi, Chiba', 'House · 2 bed', '$190,000', 'House', '2', '164m²']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_2f456691-6783-11f1-bd67-a6ae20f6eefe_f057161781beb.jpg', 'Funabashi, Chiba', 'House · 4 bed', '$190,000', 'House', '4', '100m²']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_1db7e5b6-6783-11f1-bd67-a6ae20f6eefe_13e10048789a3.jpg', 'Funabashi, Chiba', 'House · 4 bed', '$190,000', 'House', '4', '110m²']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_105088de-6783-11f1-bd67-a6ae20f6eefe_9b30faf663399.jpg', 'Funabashi, Chiba', 'House · 4 bed', '$190,000', 'House', '4', '132m²']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_ffaf0d59-6782-11f1-bd67-a6ae20f6eefe_72afa45af635d.jpg', 'Funabashi, Chiba', 'House · 4 bed', '$190,000', 'House', '4', '108m²']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_d14c829f-6782-11f1-bd67-a6ae20f6eefe_681cf267989bb.jpg', 'Funabashi, Chiba', 'House, Apartment, Land · 4 bed', '$190,000', 'House, Apartment, Land', '4', '82m²']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_bf0de440-6782-11f1-bd67-a6ae20f6eefe_5bf4d0c8d5272.jpg', 'Funabashi, Chiba', 'House, Land · 3 bed', '$190,000', 'House, Land', '3', '115m²']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_afb49e4a-6782-11f1-bd67-a6ae20f6eefe_226915fcfa2c7.jpg', 'Funabashi, Chiba', 'House, Land · 3 bed', '$190,000', 'House, Land', '3', '92m²']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_9e7d9825-6782-11f1-bd67-a6ae20f6eefe_2f8fdbc87519f.jpg', 'Funabashi, Chiba', 'House · 3 bed', '$190,000', 'House', '3', '156m²']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_87b4a906-6782-11f1-bd67-a6ae20f6eefe_58790b3690bdf.jpg', 'Funabashi, Chiba', 'House · 3 bed', '$190,000', 'House', '3', '156m²']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_532e90ab-6782-11f1-bd67-a6ae20f6eefe_512bde00d5895.jpg', 'Funabashi, Chiba', 'House, Land · 4 bed', '$190,000', 'House, Land', '4', '83m²']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_41bf4b42-6782-11f1-bd67-a6ae20f6eefe_c3387bd3f1219.jpg', 'Inzai, Chiba', 'House · 8 bed', '$590,000', 'House', '8', '5,130m²']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_31b047cc-6782-11f1-bd67-a6ae20f6eefe_8d4da2081b976.jpg', 'Ichigawa, Chiba', 'House · 1 bed', '$400,000', 'House', '1', '65m²']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_1fd833b2-6782-11f1-bd67-a6ae20f6eefe_10dfcc7a6c333.jpg', 'Kamagaya, Chiba', 'House · 5 bed', '$240,000', 'House', '5', '184m²']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_1173de5e-6782-11f1-bd67-a6ae20f6eefe_2307dfa762061.jpg', 'Ichigawa, Chiba', 'House · 3 bed', '$140,000', 'House', '3', '75m²']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_cb59448f-677f-11f1-bd67-a6ae20f6eefe_7e4901a0e8881.jpg', 'Funabashi, Chiba', 'Apartment, Land · 2 bed', '$300,000', 'Apartment, Land', '2', '-']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_94bc2ff5-677f-11f1-bd67-a6ae20f6eefe_9ff8328c49ac6.jpg', 'Funabashi, Chiba', 'Apartment, Land · 2 bed', '$300,000', 'Apartment, Land', '2', '-']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_3cdc9121-677f-11f1-bd67-a6ae20f6eefe_9958f0e82bde7.jpg', 'Funabashi, Chiba', 'Apartment · 2 bed', '$310,000', 'Apartment', '2', '-']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_1c92905a-677f-11f1-bd67-a6ae20f6eefe_f447162374150.jpg', 'Ichigawa, Chiba', 'Apartment, Land · 3 bed', '$320,000', 'Apartment, Land', '3', '-']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_090cc72f-677f-11f1-bd67-a6ae20f6eefe_6d188a7cbe74c.jpg', 'Ichigawa, Chiba', 'Apartment, Land · 3 bed', '$190,000', 'Apartment, Land', '3', '-']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_e9b5cb7d-677e-11f1-bd67-a6ae20f6eefe_0bb3b030bb3e7.jpg', 'Funabashi, Chiba', 'House · 4 bed', '$190,000', 'House', '4', '99m²']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_d78cbbd6-677e-11f1-bd67-a6ae20f6eefe_9185cffbafd4a.jpg', 'Funabashi, Chiba', 'House, Land · 3 bed', '$190,000', 'House, Land', '3', '101m²']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_c1ccd6a0-677e-11f1-bd67-a6ae20f6eefe_bb6a1ed183b15.jpg', 'Funabashi, Chiba', 'House, Apartment, Land · 3 bed', '$200,000', 'House, Apartment, Land', '3', '111m²']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_b5bb757a-677e-11f1-bd67-a6ae20f6eefe_4117fe60697df.jpg', 'Funabashi, Chiba', 'House, Land · 5 bed', '$200,000', 'House, Land', '5', '190m²']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_8bd764c3-677e-11f1-bd67-a6ae20f6eefe_c5d8ba000084c.jpg', 'Funabashi, Chiba', 'House · 4 bed', '$200,000', 'House', '4', '138m²']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_79b84326-677e-11f1-bd67-a6ae20f6eefe_357d28b96caef.jpg', 'Funabashi, Chiba', 'House · 3 bed', '$200,000', 'House', '3', '100m²']

In [6]:

last_location = ''

for match in table:
    tds = match.find_all('td')

    if len(tds) >= 5:
        image = tds[0].text.strip()
        
        location = tds[1].text.strip()
        if not location:
            location = last_location
        else:
            last_location = location

        price = tds[2].text.strip()
        types = tds[3].text.strip()
        beds = tds[4].text.strip()
        house = tds[5].text.strip() if len(tds) > 5 else ''

        print([image, location, price, types, beds, house])
    #length = len(df)
    #df.loc[length] = [date, home, score, away]

['', 'Ichigawa, Chiba\nApartment, Land · 3 bed', '$170,000', 'Apartment, Land', '3', '-']
['', 'Funabashi, Chiba\nHouse · 3 bed', '$180,000', 'House', '3', '96m²']
['', 'Funabashi, Chiba\nHouse · 3 bed', '$180,000', 'House', '3', '128m²']
['', 'Funabashi, Chiba\nHouse, Land · 5 bed', '$190,000', 'House, Land', '5', '136m²']
['', 'Funabashi, Chiba\nHouse · 2 bed', '$190,000', 'House', '2', '164m²']
['', 'Funabashi, Chiba\nHouse · 4 bed', '$190,000', 'House', '4', '100m²']
['', 'Funabashi, Chiba\nHouse · 4 bed', '$190,000', 'House', '4', '110m²']
['', 'Funabashi, Chiba\nHouse · 4 bed', '$190,000', 'House', '4', '132m²']
['', 'Funabashi, Chiba\nHouse · 4 bed', '$190,000', 'House', '4', '108m²']
['', 'Funabashi, Chiba\nHouse, Apartment, Land · 4 bed', '$190,000', 'House, Apartment, Land', '4', '82m²']
['', 'Funabashi, Chiba\nHouse, Land · 3 bed', '$190,000', 'House, Land', '3', '115m²']
['', 'Funabashi, Chiba\nHouse, Land · 3 bed', '$190,000', 'House, Land', '3', '92m²']
['', 'Funabashi, Chiba\nHouse · 3 bed', '$190,000', 'House', '3', '156m²']
['', 'Funabashi, Chiba\nHouse · 3 bed', '$190,000', 'House', '3', '156m²']
['', 'Funabashi, Chiba\nHouse, Land · 4 bed', '$190,000', 'House, Land', '4', '83m²']
['', 'Inzai, Chiba\nHouse · 8 bed', '$590,000', 'House', '8', '5,130m²']
['', 'Ichigawa, Chiba\nHouse · 1 bed', '$400,000', 'House', '1', '65m²']
['', 'Kamagaya, Chiba\nHouse · 5 bed', '$240,000', 'House', '5', '184m²']
['', 'Ichigawa, Chiba\nHouse · 3 bed', '$140,000', 'House', '3', '75m²']
['', 'Funabashi, Chiba\nApartment, Land · 2 bed', '$300,000', 'Apartment, Land', '2', '-']
['', 'Funabashi, Chiba\nApartment, Land · 2 bed', '$300,000', 'Apartment, Land', '2', '-']
['', 'Funabashi, Chiba\nApartment · 2 bed', '$310,000', 'Apartment', '2', '-']
['', 'Ichigawa, Chiba\nApartment, Land · 3 bed', '$320,000', 'Apartment, Land', '3', '-']
['', 'Ichigawa, Chiba\nApartment, Land · 3 bed', '$190,000', 'Apartment, Land', '3', '-']
['', 'Funabashi, Chiba\nHouse · 4 bed', '$190,000', 'House', '4', '99m²']
['', 'Funabashi, Chiba\nHouse, Land · 3 bed', '$190,000', 'House, Land', '3', '101m²']
['', 'Funabashi, Chiba\nHouse, Apartment, Land · 3 bed', '$200,000', 'House, Apartment, Land', '3', '111m²']
['', 'Funabashi, Chiba\nHouse, Land · 5 bed', '$200,000', 'House, Land', '5', '190m²']
['', 'Funabashi, Chiba\nHouse · 4 bed', '$200,000', 'House', '4', '138m²']
['', 'Funabashi, Chiba\nHouse · 3 bed', '$200,000', 'House', '3', '100m²']

In [7]:
akiya = []

for tables in table[1:]:
    tds = tables.find_all('td')

    # 🖼️ Image
    img_tag = tds[0].find('img') if len(tds) > 0 else None
    image = img_tag.get('src') or img_tag.get('data-src') if img_tag else ''
    price = tds[2].text.strip() if len(tds) > 2 else ''
    type = tds[3].text.strip() if len(tds) > 3 else ''
    beds = tds[4].text.strip() if len(tds) > 4 else ''
    land = tds[5].text.strip() if len(tds) > 5 else ''
    house = tds[6].text.strip() if len(tds) > 6 else ''
    konbini = tds[7].text.strip() if len(tds) > 7 else ''

    # 📍 Location (STRICT: only accept real location)
    if len(tds) > 1: # this condition will check if there is  a value and if not it will return ''
        raw = tds[1].text.strip()

        # ✅ Only accept if it's really a location
        if raw and ',' in raw: # this code will check if there is a comma in the location which is a common format for locations (e.g., "Tokyo, Japan")
            location = raw.split('\n')[0]
        else:
            location = ''   # 👈 ALWAYS empty if invalid
    else:
        location = ''

    akiya.append([image, location, price, type, beds, land, house, konbini])

    print([image, location, price, type, beds, land, house, konbini])

['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_9ad0c743-6783-11f1-bd67-a6ae20f6eefe_85d3f789ee341.jpg', 'Ichigawa, Chiba', '$170,000', 'Apartment, Land', '3', '-', '65m²', 'Family Mart (4 min)']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_8a7ccfd8-6783-11f1-bd67-a6ae20f6eefe_9e7e9b498ac14.jpg', 'Funabashi, Chiba', '$180,000', 'House', '3', '96m²', '93m²', 'Seven Eleven (6 min)']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_68bb6f22-6783-11f1-bd67-a6ae20f6eefe_402b0fd529119.jpg', 'Funabashi, Chiba', '$180,000', 'House', '3', '128m²', '93m²', 'Family Mart (2 min)']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_5681eb20-6783-11f1-bd67-a6ae20f6eefe_fbf22b9858ae9.jpg', 'Funabashi, Chiba', '$190,000', 'House, Land', '5', '136m²', '132m²', 'Lawson (6 min)']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_429f4df0-6783-11f1-bd67-a6ae20f6eefe_6243a911bb850.jpg', 'Funabashi, Chiba', '$190,000', 'House', '2', '164m²', '91m²', 'Lawson (4 min)']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_2f456691-6783-11f1-bd67-a6ae20f6eefe_f057161781beb.jpg', 'Funabashi, Chiba', '$190,000', 'House', '4', '100m²', '98m²', '-']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_1db7e5b6-6783-11f1-bd67-a6ae20f6eefe_13e10048789a3.jpg', 'Funabashi, Chiba', '$190,000', 'House', '4', '110m²', '100m²', 'Family Mart (5 min)']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_105088de-6783-11f1-bd67-a6ae20f6eefe_9b30faf663399.jpg', 'Funabashi, Chiba', '$190,000', 'House', '4', '132m²', '101m²', 'Family Mart (5 min)']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_ffaf0d59-6782-11f1-bd67-a6ae20f6eefe_72afa45af635d.jpg', 'Funabashi, Chiba', '$190,000', 'House', '4', '108m²', '98m²', 'Seven Eleven (3 min)']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_d14c829f-6782-11f1-bd67-a6ae20f6eefe_681cf267989bb.jpg', 'Funabashi, Chiba', '$190,000', 'House, Apartment, Land', '4', '82m²', '81m²', 'Lawson (1 min)']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_bf0de440-6782-11f1-bd67-a6ae20f6eefe_5bf4d0c8d5272.jpg', 'Funabashi, Chiba', '$190,000', 'House, Land', '3', '115m²', '96m²', 'Lawson (9 min)']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_afb49e4a-6782-11f1-bd67-a6ae20f6eefe_226915fcfa2c7.jpg', 'Funabashi, Chiba', '$190,000', 'House, Land', '3', '92m²', '78m²', 'Daily Yamazaki (7 min)']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_9e7d9825-6782-11f1-bd67-a6ae20f6eefe_2f8fdbc87519f.jpg', 'Funabashi, Chiba', '$190,000', 'House', '3', '156m²', '105m²', 'Family Mart (8 min)']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_87b4a906-6782-11f1-bd67-a6ae20f6eefe_58790b3690bdf.jpg', 'Funabashi, Chiba', '$190,000', 'House', '3', '156m²', '105m²', 'Family Mart (7 min)']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_532e90ab-6782-11f1-bd67-a6ae20f6eefe_512bde00d5895.jpg', 'Funabashi, Chiba', '$190,000', 'House, Land', '4', '83m²', '94m²', 'Sunkus (7 min)']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_41bf4b42-6782-11f1-bd67-a6ae20f6eefe_c3387bd3f1219.jpg', 'Inzai, Chiba', '$590,000', 'House', '8', '5,130m²', '266m²', 'Family Mart (11 min)']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_31b047cc-6782-11f1-bd67-a6ae20f6eefe_8d4da2081b976.jpg', 'Ichigawa, Chiba', '$400,000', 'House', '1', '65m²', '107m²', 'Seven Eleven (3 min)']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_1fd833b2-6782-11f1-bd67-a6ae20f6eefe_10dfcc7a6c333.jpg', 'Kamagaya, Chiba', '$240,000', 'House', '5', '184m²', '148m²', '-']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_1173de5e-6782-11f1-bd67-a6ae20f6eefe_2307dfa762061.jpg', 'Ichigawa, Chiba', '$140,000', 'House', '3', '75m²', '73m²', 'Seven Eleven (8 min)']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_cb59448f-677f-11f1-bd67-a6ae20f6eefe_7e4901a0e8881.jpg', 'Funabashi, Chiba', '$300,000', 'Apartment, Land', '2', '-', '85m²', 'Family Mart (2 min)']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_94bc2ff5-677f-11f1-bd67-a6ae20f6eefe_9ff8328c49ac6.jpg', 'Funabashi, Chiba', '$300,000', 'Apartment, Land', '2', '-', '65m²', 'Lawson Store 100 (1 min)']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_3cdc9121-677f-11f1-bd67-a6ae20f6eefe_9958f0e82bde7.jpg', 'Funabashi, Chiba', '$310,000', 'Apartment', '2', '-', '52m²', 'Family Mart (1 min)']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_1c92905a-677f-11f1-bd67-a6ae20f6eefe_f447162374150.jpg', 'Ichigawa, Chiba', '$320,000', 'Apartment, Land', '3', '-', '75m²', 'Seven Eleven (5 min)']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_090cc72f-677f-11f1-bd67-a6ae20f6eefe_6d188a7cbe74c.jpg', 'Ichigawa, Chiba', '$190,000', 'Apartment, Land', '3', '-', '67m²', 'Lawson Store 100 (5 min)']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_e9b5cb7d-677e-11f1-bd67-a6ae20f6eefe_0bb3b030bb3e7.jpg', 'Funabashi, Chiba', '$190,000', 'House', '4', '99m²', '90m²', 'Lawson (1 min)']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_d78cbbd6-677e-11f1-bd67-a6ae20f6eefe_9185cffbafd4a.jpg', 'Funabashi, Chiba', '$190,000', 'House, Land', '3', '101m²', '95m²', 'Lawson (4 min)']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_c1ccd6a0-677e-11f1-bd67-a6ae20f6eefe_bb6a1ed183b15.jpg', 'Funabashi, Chiba', '$200,000', 'House, Apartment, Land', '3', '111m²', '99m²', 'Sunkus (3 min)']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_b5bb757a-677e-11f1-bd67-a6ae20f6eefe_4117fe60697df.jpg', 'Funabashi, Chiba', '$200,000', 'House, Land', '5', '190m²', '149m²', 'Family Mart (6 min)']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_8bd764c3-677e-11f1-bd67-a6ae20f6eefe_c5d8ba000084c.jpg', 'Funabashi, Chiba', '$200,000', 'House', '4', '138m²', '92m²', 'Mini Stop (4 min)']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_79b84326-677e-11f1-bd67-a6ae20f6eefe_357d28b96caef.jpg', 'Funabashi, Chiba', '$200,000', 'House', '3', '100m²', '101m²', 'Mini Stop (5 min)']

In [8]:
soup = soup.find('table')
soup

<table class="min-w-full divide-y divide-gray-200 dark:divide-gray-700 bg-white dark:bg-gray-800">
<thead class="bg-gray-50 dark:bg-gray-800">
<tr>
<th class="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Image</th>
<th class="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Location</th>
<th class="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Price</th>
<th class="hidden sm:table-cell px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Type</th>
<th class="hidden md:table-cell px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Beds</th>
<th class="hidden lg:table-cell px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Land</th>
<th class="hidden md:table-cell px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">House</th>
<th class="hidden lg:table-cell px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Konbini</th>
<th class="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Actions</th>
</tr>
</thead>
<tbody class="divide-y divide-gray-200 dark:divide-gray-700" id="properties-table-body">
<tr class="hover:bg-gray-50 dark:hover:bg-gray-800">
<td class="px-4 py-3">
<a aria-label="View property details" class="block w-16 h-16 sm:w-20 sm:h-20" href="/property/53616c7465645f5f056cab13882022501b5f5d5892500fe3d98a6a9fc138f7c2">
<img alt="Property" class="w-full h-full object-cover rounded" loading="lazy" onerror="this.src='/assets/images/no-image.svg'" src="https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_9ad0c743-6783-11f1-bd67-a6ae20f6eefe_85d3f789ee341.jpg"/>
</a>
</td>
<td class="px-4 py-3 text-sm text-gray-900 dark:text-gray-100">
<div>Ichigawa, <a class="hover:text-blue-600 dark:hover:text-blue-400 transition-colors" href="/prefecture/chiba">Chiba</a></div>
<div class="sm:hidden text-xs text-gray-500 dark:text-gray-400 mt-1">Apartment, Land · 3 bed</div>
</td>
<td class="px-4 py-3 text-sm font-semibold text-gray-900 dark:text-gray-100 whitespace-nowrap" data-original-price="26990000">$170,000</td>
<td class="hidden sm:table-cell px-4 py-3 text-sm text-gray-600 dark:text-gray-400">Apartment, Land</td>
<td class="hidden md:table-cell px-4 py-3 text-sm text-center text-gray-600 dark:text-gray-400">3</td>
<td class="hidden lg:table-cell px-4 py-3 text-sm text-right text-gray-600 dark:text-gray-400" data-original-land-size="">-</td>
<td class="hidden md:table-cell px-4 py-3 text-sm text-right text-gray-600 dark:text-gray-400" data-original-house-size="65.40">65m²</td>
<td class="hidden lg:table-cell px-4 py-3 text-sm text-gray-600 dark:text-gray-400">Family Mart (4 min)</td>
<td class="px-4 py-3">
<div class="flex items-center space-x-2">
<button aria-label="Save property" class="p-2 text-gray-400 hover:text-pink-500 transition-all" data-property-id="1322669" data-saved="false">
<svg class="w-5 h-5 fill-current" stroke="currentColor" stroke-width="2" viewbox="0 0 24 24">
<path d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" stroke-linecap="round" stroke-linejoin="round"></path>
</svg>
</button>
<a class="text-blue-600 hover:text-blue-800 dark:text-blue-400 dark:hover:text-blue-300 text-sm whitespace-nowrap" href="/property/53616c7465645f5f056cab13882022501b5f5d5892500fe3d98a6a9fc138f7c2">
                                View →
                            </a>
</div>
</td>
</tr>
<tr class="hover:bg-gray-50 dark:hover:bg-gray-800">
<td class="px-4 py-3">
<a aria-label="View property details" class="block w-16 h-16 sm:w-20 sm:h-20" href="/property/53616c7465645f5f34dd752ce06276ce0a373428af340e3a987311ae0e491159">
<img alt="Property" class="w-full h-full object-cover rounded" loading="lazy" onerror="this.src='/assets/images/no-image.svg'" src="https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_8a7ccfd8-6783-11f1-bd67-a6ae20f6eefe_9e7e9b498ac14.jpg"/>
</a>
</td>
<td class="px-4 py-3 text-sm text-gray-900 dark:text-gray-100">
<div>Funabashi, <a class="hover:text-blue-600 dark:hover:text-blue-400 transition-colors" href="/prefecture/chiba">Chiba</a></div>
<div class="sm:hidden text-xs text-gray-500 dark:text-gray-400 mt-1">House · 3 bed</div>
</td>
<td class="px-4 py-3 text-sm font-semibold text-gray-900 dark:text-gray-100 whitespace-nowrap" data-original-price="29500000">$180,000</td>
<td class="hidden sm:table-cell px-4 py-3 text-sm text-gray-600 dark:text-gray-400">House</td>
<td class="hidden md:table-cell px-4 py-3 text-sm text-center text-gray-600 dark:text-gray-400">3</td>
<td class="hidden lg:table-cell px-4 py-3 text-sm text-right text-gray-600 dark:text-gray-400" data-original-land-size="96.00">96m²</td>
<td class="hidden md:table-cell px-4 py-3 text-sm text-right text-gray-600 dark:text-gray-400" data-original-house-size="93.10">93m²</td>
<td class="hidden lg:table-cell px-4 py-3 text-sm text-gray-600 dark:text-gray-400">Seven Eleven (6 min)</td>
<td class="px-4 py-3">
<div class="flex items-center space-x-2">
<button aria-label="Save property" class="p-2 text-gray-400 hover:text-pink-500 transition-all" data-property-id="1322668" data-saved="false">
<svg class="w-5 h-5 fill-current" stroke="currentColor" stroke-width="2" viewbox="0 0 24 24">
<path d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" stroke-linecap="round" stroke-linejoin="round"></path>
</svg>
</button>
<a class="text-blue-600 hover:text-blue-800 dark:text-blue-400 dark:hover:text-blue-300 text-sm whitespace-nowrap" href="/property/53616c7465645f5f34dd752ce06276ce0a373428af340e3a987311ae0e491159">
                                View →
                            </a>
</div>
</td>
</tr>
<tr class="hover:bg-gray-50 dark:hover:bg-gray-800">
<td class="px-4 py-3">
<a aria-label="View property details" class="block w-16 h-16 sm:w-20 sm:h-20" href="/property/53616c7465645f5fdb2a37c4f77e9066b655a6df6655798cb96cbbf198e6e248">
<img alt="Property" class="w-full h-full object-cover rounded" loading="lazy" onerror="this.src='/assets/images/no-image.svg'" src="https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_68bb6f22-6783-11f1-bd67-a6ae20f6eefe_402b0fd529119.jpg"/>
</a>
</td>
<td class="px-4 py-3 text-sm text-gray-900 dark:text-gray-100">
<div>Funabashi, <a class="hover:text-blue-600 dark:hover:text-blue-400 transition-colors" href="/prefecture/chiba">Chiba</a></div>
<div class="sm:hidden text-xs text-gray-500 dark:text-gray-400 mt-1">House · 3 bed</div>
</td>
<td class="px-4 py-3 text-sm font-semibold text-gray-900 dark:text-gray-100 whitespace-nowrap" data-original-price="29500000">$180,000</td>
<td class="hidden sm:table-cell px-4 py-3 text-sm text-gray-600 dark:text-gray-400">House</td>
<td class="hidden md:table-cell px-4 py-3 text-sm text-center text-gray-600 dark:text-gray-400">3</td>
<td class="hidden lg:table-cell px-4 py-3 text-sm text-right text-gray-600 dark:text-gray-400" data-original-land-size="128.17">128m²</td>
<td class="hidden md:table-cell px-4 py-3 text-sm text-right text-gray-600 dark:text-gray-400" data-original-house-size="93.36">93m²</td>
<td class="hidden lg:table-cell px-4 py-3 text-sm text-gray-600 dark:text-gray-400">Family Mart (2 min)</td>
<td class="px-4 py-3">
<div class="flex items-center space-x-2">
<button aria-label="Save property" class="p-2 text-gray-400 hover:text-pink-500 transition-all" data-property-id="1322666" data-saved="false">
<svg class="w-5 h-5 fill-current" stroke="currentColor" stroke-width="2" viewbox="0 0 24 24">
<path d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" stroke-linecap="round" stroke-linejoin="round"></path>
</svg>
</button>
<a class="text-blue-600 hover:text-blue-800 dark:text-blue-400 dark:hover:text-blue-300 text-sm whitespace-nowrap" href="/property/53616c7465645f5fdb2a37c4f77e9066b655a6df6655798cb96cbbf198e6e248">
                                View →
                            </a>
</div>
</td>
</tr>
<tr class="hover:bg-gray-50 dark:hover:bg-gray-800">
<td class="px-4 py-3">
<a aria-label="View property details" class="block w-16 h-16 sm:w-20 sm:h-20" href="/property/53616c7465645f5f2c5af16bd649ae937962ccc76fcbaae510c7c47047db13f2">
<img alt="Property" class="w-full h-full object-cover rounded" loading="lazy" onerror="this.src='/assets/images/no-image.svg'" src="https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_5681eb20-6783-11f1-bd67-a6ae20f6eefe_fbf22b9858ae9.jpg"/>
</a>
</td>
<td class="px-4 py-3 text-sm text-gray-900 dark:text-gray-100">
<div>Funabashi, <a class="hover:text-blue-600 dark:hover:text-blue-400 transition-colors" href="/prefecture/chiba">Chiba</a></div>
<div class="sm:hidden text-xs text-gray-500 dark:text-gray-400 mt-1">House, Land · 5 bed</div>
</td>
<td class="px-4 py-3 text-sm font-semibold text-gray-900 dark:text-gray-100 whitespace-nowrap" data-original-price="29800000">$190,000</td>
<td class="hidden sm:table-cell px-4 py-3 text-sm text-gray-600 dark:text-gray-400">House, Land</td>
<td class="hidden md:table-cell px-4 py-3 text-sm text-center text-gray-600 dark:text-gray-400">5</td>
<td class="hidden lg:table-cell px-4 py-3 text-sm text-right text-gray-600 dark:text-gray-400" data-original-land-size="136.00">136m²</td>
<td class="hidden md:table-cell px-4 py-3 text-sm text-right text-gray-600 dark:text-gray-400" data-original-house-size="132.92">132m²</td>
<td class="hidden lg:table-cell px-4 py-3 text-sm text-gray-600 dark:text-gray-400">Lawson (6 min)</td>
<td class="px-4 py-3">
<div class="flex items-center space-x-2">
<button aria-label="Save property" class="p-2 text-gray-400 hover:text-pink-500 transition-all" data-property-id="1322665" data-saved="false">
<svg class="w-5 h-5 fill-current" stroke="currentColor" stroke-width="2" viewbox="0 0 24 24">
<path d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" stroke-linecap="round" stroke-linejoin="round"></path>
</svg>
</button>
<a class="text-blue-600 hover:text-blue-800 dark:text-blue-400 dark:hover:text-blue-300 text-sm whitespace-nowrap" href="/property/53616c7465645f5f2c5af16bd649ae937962ccc76fcbaae510c7c47047db13f2">
                                View →
                            </a>
</div>
</td>
</tr>
<tr class="hover:bg-gray-50 dark:hover:bg-gray-800">
<td class="px-4 py-3">
<a aria-label="View property details" class="block w-16 h-16 sm:w-20 sm:h-20" href="/property/53616c7465645f5f819c0af978e062db67d19591dfde936eb1bffb7a3916792b">
<img alt="Property" class="w-full h-full object-cover rounded" loading="lazy" onerror="this.src='/assets/images/no-image.svg'" src="https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_429f4df0-6783-11f1-bd67-a6ae20f6eefe_6243a911bb850.jpg"/>
</a>
</td>
<td class="px-4 py-3 text-sm text-gray-900 dark:text-gray-100">
<div>Funabashi, <a class="hover:text-blue-600 dark:hover:text-blue-400 transition-colors" href="/prefecture/chiba">Chiba</a></div>
<div class="sm:hidden text-xs text-gray-500 dark:text-gray-400 mt-1">House · 2 bed</div>
</td>
<td class="px-4 py-3 text-sm font-semibold text-gray-900 dark:text-gray-100 whitespace-nowrap" data-original-price="29800000">$190,000</td>
<td class="hidden sm:table-cell px-4 py-3 text-sm text-gray-600 dark:text-gray-400">House</td>
<td class="hidden md:table-cell px-4 py-3 text-sm text-center text-gray-600 dark:text-gray-400">2</td>
<td class="hidden lg:table-cell px-4 py-3 text-sm text-right text-gray-600 dark:text-gray-400" data-original-land-size="164.85">164m²</td>
<td class="hidden md:table-cell px-4 py-3 text-sm text-right text-gray-600 dark:text-gray-400" data-original-house-size="91.91">91m²</td>
<td class="hidden lg:table-cell px-4 py-3 text-sm text-gray-600 dark:text-gray-400">Lawson (4 min)</td>
<td class="px-4 py-3">
<div class="flex items-center space-x-2">
<button aria-label="Save property" class="p-2 text-gray-400 hover:text-pink-500 transition-all" data-property-id="1322664" data-saved="false">
<svg class="w-5 h-5 fill-current" stroke="currentColor" stroke-width="2" viewbox="0 0 24 24">
<path d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" stroke-linecap="round" stroke-linejoin="round"></path>
</svg>
</button>
<a class="text-blue-600 hover:text-blue-800 dark:text-blue-400 dark:hover:text-blue-300 text-sm whitespace-nowrap" href="/property/53616c7465645f5f819c0af978e062db67d19591dfde936eb1bffb7a3916792b">
                                View →
                            </a>
</div>
</td>
</tr>
<tr class="hover:bg-gray-50 dark:hover:bg-gray-800">
<td class="px-4 py-3">
<a aria-label="View property details" class="block w-16 h-16 sm:w-20 sm:h-20" href="/property/53616c7465645f5f00a4da7d11c94941033cf257ffbf0fdc4006fb4b990da204">
<img alt="Property" class="w-full h-full object-cover rounded" loading="lazy" onerror="this.src='/assets/images/no-image.svg'" src="https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_2f456691-6783-11f1-bd67-a6ae20f6eefe_f057161781beb.jpg"/>
</a>
</td>
<td class="px-4 py-3 text-sm text-gray-900 dark:text-gray-100">
<div>Funabashi, <a class="hover:text-blue-600 dark:hover:text-blue-400 transition-colors" href="/prefecture/chiba">Chiba</a></div>
<div class="sm:hidden text-xs text-gray-500 dark:text-gray-400 mt-1">House · 4 bed</div>
</td>
<td class="px-4 py-3 text-sm font-semibold text-gray-900 dark:text-gray-100 whitespace-nowrap" data-original-price="29800000">$190,000</td>
<td class="hidden sm:table-cell px-4 py-3 text-sm text-gray-600 dark:text-gray-400">House</td>
<td class="hidden md:table-cell px-4 py-3 text-sm text-center text-gray-600 dark:text-gray-400">4</td>
<td class="hidden lg:table-cell px-4 py-3 text-sm text-right text-gray-600 dark:text-gray-400" data-original-land-size="100.38">100m²</td>
<td class="hidden md:table-cell px-4 py-3 text-sm text-right text-gray-600 dark:text-gray-400" data-original-house-size="98.32">98m²</td>
<td class="hidden lg:table-cell px-4 py-3 text-sm text-gray-600 dark:text-gray-400">-</td>
<td class="px-4 py-3">
<div class="flex items-center space-x-2">
<button aria-label="Save property" class="p-2 text-gray-400 hover:text-pink-500 transition-all" data-property-id="1322663" data-saved="false">
<svg class="w-5 h-5 fill-current" stroke="currentColor" stroke-width="2" viewbox="0 0 24 24">
<path d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" stroke-linecap="round" stroke-linejoin="round"></path>
</svg>
</button>
<a class="text-blue-600 hover:text-blue-800 dark:text-blue-400 dark:hover:text-blue-300 text-sm whitespace-nowrap" href="/property/53616c7465645f5f00a4da7d11c94941033cf257ffbf0fdc4006fb4b990da204">
                                View →
                            </a>
</div>
</td>
</tr>
<tr class="hover:bg-gray-50 dark:hover:bg-gray-800">
<td class="px-4 py-3">
<a aria-label="View property details" class="block w-16 h-16 sm:w-20 sm:h-20" href="/property/53616c7465645f5ff246d87a86b903d9db38c13ab509afeaa9a624294aa0d840">
<img alt="Property" class="w-full h-full object-cover rounded" loading="lazy" onerror="this.src='/assets/images/no-image.svg'" src="https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_1db7e5b6-6783-11f1-bd67-a6ae20f6eefe_13e10048789a3.jpg"/>
</a>
</td>
<td class="px-4 py-3 text-sm text-gray-900 dark:text-gray-100">
<div>Funabashi, <a class="hover:text-blue-600 dark:hover:text-blue-400 transition-colors" href="/prefecture/chiba">Chiba</a></div>
<div class="sm:hidden text-xs text-gray-500 dark:text-gray-400 mt-1">House · 4 bed</div>
</td>
<td class="px-4 py-3 text-sm font-semibold text-gray-900 dark:text-gray-100 whitespace-nowrap" data-original-price="29800000">$190,000</td>
<td class="hidden sm:table-cell px-4 py-3 text-sm text-gray-600 dark:text-gray-400">House</td>
<td class="hidden md:table-cell px-4 py-3 text-sm text-center text-gray-600 dark:text-gray-400">4</td>
<td class="hidden lg:table-cell px-4 py-3 text-sm text-right text-gray-600 dark:text-gray-400" data-original-land-size="110.04">110m²</td>
<td class="hidden md:table-cell px-4 py-3 text-sm text-right text-gray-600 dark:text-gray-400" data-original-house-size="100.92">100m²</td>
<td class="hidden lg:table-cell px-4 py-3 text-sm text-gray-600 dark:text-gray-400">Family Mart (5 min)</td>
<td class="px-4 py-3">
<div class="flex items-center space-x-2">
<button aria-label="Save property" class="p-2 text-gray-400 hover:text-pink-500 transition-all" data-property-id="1322662" data-saved="false">
<svg class="w-5 h-5 fill-current" stroke="currentColor" stroke-width="2" viewbox="0 0 24 24">
<path d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" stroke-linecap="round" stroke-linejoin="round"></path>
</svg>
</button>
<a class="text-blue-600 hover:text-blue-800 dark:text-blue-400 dark:hover:text-blue-300 text-sm whitespace-nowrap" href="/property/53616c7465645f5ff246d87a86b903d9db38c13ab509afeaa9a624294aa0d840">
                                View →
                            </a>
</div>
</td>
</tr>
<tr class="hover:bg-gray-50 dark:hover:bg-gray-800">
<td class="px-4 py-3">
<a aria-label="View property details" class="block w-16 h-16 sm:w-20 sm:h-20" href="/property/53616c7465645f5ff4689e16a5369ea97914e167d746cf87cb44a5ca7d5470bc">
<img alt="Property" class="w-full h-full object-cover rounded" loading="lazy" onerror="this.src='/assets/images/no-image.svg'" src="https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_105088de-6783-11f1-bd67-a6ae20f6eefe_9b30faf663399.jpg"/>
</a>
</td>
<td class="px-4 py-3 text-sm text-gray-900 dark:text-gray-100">
<div>Funabashi, <a class="hover:text-blue-600 dark:hover:text-blue-400 transition-colors" href="/prefecture/chiba">Chiba</a></div>
<div class="sm:hidden text-xs text-gray-500 dark:text-gray-400 mt-1">House · 4 bed</div>
</td>
<td class="px-4 py-3 text-sm font-semibold text-gray-900 dark:text-gray-100 whitespace-nowrap" data-original-price="29800000">$190,000</td>
<td class="hidden sm:table-cell px-4 py-3 text-sm text-gray-600 dark:text-gray-400">House</td>
<td class="hidden md:table-cell px-4 py-3 text-sm text-center text-gray-600 dark:text-gray-400">4</td>
<td class="hidden lg:table-cell px-4 py-3 text-sm text-right text-gray-600 dark:text-gray-400" data-original-land-size="132.00">132m²</td>
<td class="hidden md:table-cell px-4 py-3 text-sm text-right text-gray-600 dark:text-gray-400" data-original-house-size="101.43">101m²</td>
<td class="hidden lg:table-cell px-4 py-3 text-sm text-gray-600 dark:text-gray-400">Family Mart (5 min)</td>
<td class="px-4 py-3">
<div class="flex items-center space-x-2">
<button aria-label="Save property" class="p-2 text-gray-400 hover:text-pink-500 transition-all" data-property-id="1322661" data-saved="false">
<svg class="w-5 h-5 fill-current" stroke="currentColor" stroke-width="2" viewbox="0 0 24 24">
<path d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" stroke-linecap="round" stroke-linejoin="round"></path>
</svg>
</button>
<a class="text-blue-600 hover:text-blue-800 dark:text-blue-400 dark:hover:text-blue-300 text-sm whitespace-nowrap" href="/property/53616c7465645f5ff4689e16a5369ea97914e167d746cf87cb44a5ca7d5470bc">
                                View →

In [9]:
header = soup.find_all('th')
table_header = [title.text.strip() for title in header]
table_header

['Image',
 'Location',
 'Price',
 'Type',
 'Beds',
 'Land',
 'House',
 'Konbini',
 'Actions']

In [10]:
df = pd.DataFrame(akiya, columns=['Image', 'Location', 'Price', 'Type', 'Beds', 'Land', 'House', 'Konbini'])
df

,Image,Location,Price,Type,Beds,Land,House,Konbini
0,https://akiyajapan.sgp1.cdn.digitaloceanspaces...,"Ichigawa, Chiba","$170,000","Apartment, Land",3,-,65m²,Family Mart (4 min)
1,https://akiyajapan.sgp1.cdn.digitaloceanspaces...,"Funabashi, Chiba","$180,000",House,3,96m²,93m²,Seven Eleven (6 min)
2,https://akiyajapan.sgp1.cdn.digitaloceanspaces...,"Funabashi, Chiba","$180,000",House,3,128m²,93m²,Family Mart (2 min)
3,https://akiyajapan.sgp1.cdn.digitaloceanspaces...,"Funabashi, Chiba","$190,000","House, Land",5,136m²,132m²,Lawson (6 min)
4,https://akiyajapan.sgp1.cdn.digitaloceanspaces...,"Funabashi, Chiba","$190,000",House,2,164m²,91m²,Lawson (4 min)
5,https://akiyajapan.sgp1.cdn.digitaloceanspaces...,"Funabashi, Chiba","$190,000",House,4,100m²,98m²,-
6,https://akiyajapan.sgp1.cdn.digitaloceanspaces...,"Funabashi, Chiba","$190,000",House,4,110m²,100m²,Family Mart (5 min)
7,https://akiyajapan.sgp1.cdn.digitaloceanspaces...,"Funabashi, Chiba","$190,000",House,4,132m²,101m²,Family Mart (5 min)
8,https://akiyajapan.sgp1.cdn.digitaloceanspaces...,"Funabashi, Chiba","$190,000",House,4,108m²,98m²,Seven Eleven (3 min)
9,https://akiyajapan.sgp1.cdn.digitaloceanspaces...,"Funabashi, Chiba","$190,000","House, Apartment, Land",4,82m²,81m²,Lawson (1 min)
10,https://akiyajapan.sgp1.cdn.digitaloceanspaces...,"Funabashi, Chiba","$190,000","House, Land",3,115m²,96m²,Lawson (9 min)
11,https://akiyajapan.sgp1.cdn.digitaloceanspaces...,"Funabashi, Chiba","$190,000","House, Land",3,92m²,78m²,Daily Yamazaki (7 min)
12,https://akiyajapan.sgp1.cdn.digitaloceanspaces...,"Funabashi, Chiba","$190,000",House,3,156m²,105m²,Family Mart (8 min)
13,https://akiyajapan.sgp1.cdn.digitaloceanspaces...,"Funabashi, Chiba","$190,000",House,3,156m²,105m²,Family Mart (7 min)
14,https://akiyajapan.sgp1.cdn.digitaloceanspaces...,"Funabashi, Chiba","$190,000","House, Land",4,83m²,94m²,Sunkus (7 min)
15,https://akiyajapan.sgp1.cdn.digitaloceanspaces...,"Inzai, Chiba","$590,000",House,8,"5,130m²",266m²,Family Mart (11 min)
16,https://akiyajapan.sgp1.cdn.digitaloceanspaces...,"Ichigawa, Chiba","$400,000",House,1,65m²,107m²,Seven Eleven (3 min)
17,https://akiyajapan.sgp1.cdn.digitaloceanspaces...,"Kamagaya, Chiba","$240,000",House,5,184m²,148m²,-
18,https://akiyajapan.sgp1.cdn.digitaloceanspaces...,"Ichigawa, Chiba","$140,000",House,3,75m²,73m²,Seven Eleven (8 min)
19,https://akiyajapan.sgp1.cdn.digitaloceanspaces...,"Funabashi, Chiba","$300,000","Apartment, Land",2,-,85m²,Family Mart (2 min)
20,https://akiyajapan.sgp1.cdn.digitaloceanspaces...,"Funabashi, Chiba","$300,000","Apartment, Land",2,-,65m²,Lawson Store 100 (1 min)
21,https://akiyajapan.sgp1.cdn.digitaloceanspaces...,"Funabashi, Chiba","$310,000",Apartment,2,-,52m²,Family Mart (1 min)
22,https://akiyajapan.sgp1.cdn.digitaloceanspaces...,"Ichigawa, Chiba","$320,000","Apartment, Land",3,-,75m²,Seven Eleven (5 min)
23,https://akiyajapan.sgp1.cdn.digitaloceanspaces...,"Ichigawa, Chiba","$190,000","Apartment, Land",3,-,67m²,Lawson Store 100 (5 min)
24,https://akiyajapan.sgp1.cdn.digitaloceanspaces...,"Funabashi, Chiba","$190,000",House,4,99m²,90m²,Lawson (1 min)
25,https://akiyajapan.sgp1.cdn.digitaloceanspaces...,"Funabashi, Chiba","$190,000","House, Land",3,101m²,95m²,Lawson (4 min)
26,https://akiyajapan.sgp1.cdn.digitaloceanspaces...,"Funabashi, Chiba","$200,000","House, Apartment, Land",3,111m²,99m²,Sunkus (3 min)
27,https://akiyajapan.sgp1.cdn.digitaloceanspaces...,"Funabashi, Chiba","$200,000","House, Land",5,190m²,149m²,Family Mart (6 min)
28,https://akiyajapan.sgp1.cdn.digitaloceanspaces...,"Funabashi, Chiba","$200,000",House,4,138m²,92m²,Mini Stop (4 min)
29,https://akiyajapan.sgp1.cdn.digitaloceanspaces...,"Funabashi, Chiba","$200,000",House,3,100m²,101m²,Mini Stop (5 min)

In [11]:
df.to_csv('akiya_data.csv', index=False)

In [12]:
fd = pd.read_csv('akiya_data.csv')
fd

,Image,Location,Price,Type,Beds,Land,House,Konbini
0,https://akiyajapan.sgp1.cdn.digitaloceanspaces...,"Ichigawa, Chiba","$170,000","Apartment, Land",3,-,65m²,Family Mart (4 min)
1,https://akiyajapan.sgp1.cdn.digitaloceanspaces...,"Funabashi, Chiba","$180,000",House,3,96m²,93m²,Seven Eleven (6 min)
2,https://akiyajapan.sgp1.cdn.digitaloceanspaces...,"Funabashi, Chiba","$180,000",House,3,128m²,93m²,Family Mart (2 min)
3,https://akiyajapan.sgp1.cdn.digitaloceanspaces...,"Funabashi, Chiba","$190,000","House, Land",5,136m²,132m²,Lawson (6 min)
4,https://akiyajapan.sgp1.cdn.digitaloceanspaces...,"Funabashi, Chiba","$190,000",House,2,164m²,91m²,Lawson (4 min)
5,https://akiyajapan.sgp1.cdn.digitaloceanspaces...,"Funabashi, Chiba","$190,000",House,4,100m²,98m²,-
6,https://akiyajapan.sgp1.cdn.digitaloceanspaces...,"Funabashi, Chiba","$190,000",House,4,110m²,100m²,Family Mart (5 min)
7,https://akiyajapan.sgp1.cdn.digitaloceanspaces...,"Funabashi, Chiba","$190,000",House,4,132m²,101m²,Family Mart (5 min)
8,https://akiyajapan.sgp1.cdn.digitaloceanspaces...,"Funabashi, Chiba","$190,000",House,4,108m²,98m²,Seven Eleven (3 min)
9,https://akiyajapan.sgp1.cdn.digitaloceanspaces...,"Funabashi, Chiba","$190,000","House, Apartment, Land",4,82m²,81m²,Lawson (1 min)
10,https://akiyajapan.sgp1.cdn.digitaloceanspaces...,"Funabashi, Chiba","$190,000","House, Land",3,115m²,96m²,Lawson (9 min)
11,https://akiyajapan.sgp1.cdn.digitaloceanspaces...,"Funabashi, Chiba","$190,000","House, Land",3,92m²,78m²,Daily Yamazaki (7 min)
12,https://akiyajapan.sgp1.cdn.digitaloceanspaces...,"Funabashi, Chiba","$190,000",House,3,156m²,105m²,Family Mart (8 min)
13,https://akiyajapan.sgp1.cdn.digitaloceanspaces...,"Funabashi, Chiba","$190,000",House,3,156m²,105m²,Family Mart (7 min)
14,https://akiyajapan.sgp1.cdn.digitaloceanspaces...,"Funabashi, Chiba","$190,000","House, Land",4,83m²,94m²,Sunkus (7 min)
15,https://akiyajapan.sgp1.cdn.digitaloceanspaces...,"Inzai, Chiba","$590,000",House,8,"5,130m²",266m²,Family Mart (11 min)
16,https://akiyajapan.sgp1.cdn.digitaloceanspaces...,"Ichigawa, Chiba","$400,000",House,1,65m²,107m²,Seven Eleven (3 min)
17,https://akiyajapan.sgp1.cdn.digitaloceanspaces...,"Kamagaya, Chiba","$240,000",House,5,184m²,148m²,-
18,https://akiyajapan.sgp1.cdn.digitaloceanspaces...,"Ichigawa, Chiba","$140,000",House,3,75m²,73m²,Seven Eleven (8 min)
19,https://akiyajapan.sgp1.cdn.digitaloceanspaces...,"Funabashi, Chiba","$300,000","Apartment, Land",2,-,85m²,Family Mart (2 min)
20,https://akiyajapan.sgp1.cdn.digitaloceanspaces...,"Funabashi, Chiba","$300,000","Apartment, Land",2,-,65m²,Lawson Store 100 (1 min)
21,https://akiyajapan.sgp1.cdn.digitaloceanspaces...,"Funabashi, Chiba","$310,000",Apartment,2,-,52m²,Family Mart (1 min)
22,https://akiyajapan.sgp1.cdn.digitaloceanspaces...,"Ichigawa, Chiba","$320,000","Apartment, Land",3,-,75m²,Seven Eleven (5 min)
23,https://akiyajapan.sgp1.cdn.digitaloceanspaces...,"Ichigawa, Chiba","$190,000","Apartment, Land",3,-,67m²,Lawson Store 100 (5 min)
24,https://akiyajapan.sgp1.cdn.digitaloceanspaces...,"Funabashi, Chiba","$190,000",House,4,99m²,90m²,Lawson (1 min)
25,https://akiyajapan.sgp1.cdn.digitaloceanspaces...,"Funabashi, Chiba","$190,000","House, Land",3,101m²,95m²,Lawson (4 min)
26,https://akiyajapan.sgp1.cdn.digitaloceanspaces...,"Funabashi, Chiba","$200,000","House, Apartment, Land",3,111m²,99m²,Sunkus (3 min)
27,https://akiyajapan.sgp1.cdn.digitaloceanspaces...,"Funabashi, Chiba","$200,000","House, Land",5,190m²,149m²,Family Mart (6 min)
28,https://akiyajapan.sgp1.cdn.digitaloceanspaces...,"Funabashi, Chiba","$200,000",House,4,138m²,92m²,Mini Stop (4 min)
29,https://akiyajapan.sgp1.cdn.digitaloceanspaces...,"Funabashi, Chiba","$200,000",House,3,100m²,101m²,Mini Stop (5 min)

# Appending Data into Existing file

In [41]:
from selenium.webdriver.common.by import By
import os

In [42]:
website = 'https://www.akiyajapan.com/search/list?categories%5B%5D=Buy&order_by=date_desc'
#path = r'D:\progaming files\Python\Jupyter\chromedriver-win64\chromedriver.exe' #chrome driver file path
#service = Service(path)
driver = webdriver.Chrome() 
driver.get(website)


table_view = driver.find_element(By.XPATH, '//*[@id="table-view-btn"]') #this line is about calling button for it to click auto 
table_view.click()


driver.execute_script("goToPage(3);")

time.sleep(3)

soup = BeautifulSoup(driver.page_source, 'html.parser')

In [43]:
table = soup.find_all('tr')

In [44]:
akiya = []

for tables in table[1:]:
    tds = tables.find_all('td')

    # 🖼️ Image
    img_tag = tds[0].find('img') if len(tds) > 0 else None
    image = img_tag.get('src') or img_tag.get('data-src') if img_tag else ''
    price = tds[2].text.strip() if len(tds) > 2 else ''
    type = tds[3].text.strip() if len(tds) > 3 else ''
    beds = tds[4].text.strip() if len(tds) > 4 else ''
    land = tds[5].text.strip() if len(tds) > 5 else ''
    house = tds[6].text.strip() if len(tds) > 6 else ''
    konbini = tds[7].text.strip() if len(tds) > 7 else ''

    # 📍 Location (STRICT: only accept real location)
    if len(tds) > 1: # this condition will check if there is  a value and if not it will return ''
        raw = tds[1].text.strip()

        # ✅ Only accept if it's really a location
        if raw and ',' in raw: # this code will check if there is a comma in the location which is a common format for locations (e.g., "Tokyo, Japan")
            location = raw.split('\n')[0]
        else:
            location = ''   # 👈 ALWAYS empty if invalid
    else:
        location = ''

    akiya.append([image, location, price, type, beds, land, house, konbini])

    print([image, location, price, type, beds, land, house, konbini])

['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_80845dc1-6226-11f1-bd67-a6ae20f6eefe_4551fe12b78e1.jpg', 'Meguro, Tokyo', '$1,030,000', 'House, Apartment, Land', '3', '70m²', '95m²', 'Lawson (2 min)']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_6dee4849-6226-11f1-bd67-a6ae20f6eefe_1b5ab7d9ce4d6.jpg', 'Meguro, Tokyo', '$1,000,000', 'House', '2', '67m²', '101m²', 'Lawson (1 min)']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_5de9df40-6226-11f1-bd67-a6ae20f6eefe_cd20081959e1c.jpg', 'Meguro, Tokyo', '$1,120,000', 'House, Apartment, Land', '3', '80m²', '93m²', 'Family Mart (2 min)']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_51f8bb84-6226-11f1-bd67-a6ae20f6eefe_8d6686ed7def8.jpg', 'Meguro, Tokyo', '$1,120,000', 'House, Land', '3', '80m²', '93m²', 'Family Mart (5 min)']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_3d38f839-6226-11f1-bd67-a6ae20f6eefe_395f1d1d0d4c7.jpg', 'Meguro, Tokyo', '$1,220,000', 'House', '4', '74m²', '128m²', 'Lawson (4 min)']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_0a596130-6226-11f1-bd67-a6ae20f6eefe_eb3be760d7518.jpg', 'Meguro, Tokyo', '$1,240,000', 'House, Land', '4', '180m²', '114m²', 'Family Mart (4 min)']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_fc58f61e-6225-11f1-bd67-a6ae20f6eefe_9d979d88c4382.jpg', 'Meguro, Tokyo', '$1,320,000', 'House, Land', '5', '135m²', '184m²', 'Lawson (4 min)']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_ecb3812e-6225-11f1-bd67-a6ae20f6eefe_06049c44d3418.jpg', 'Meguro, Tokyo', '$1,380,000', 'House, Land', '4', '98m²', '104m²', 'Family Mart (4 min)']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_d9d5dfc4-6225-11f1-bd67-a6ae20f6eefe_d87ea81e4bd1a.jpg', 'Meguro, Tokyo', '$1,490,000', 'House, Apartment, Land', '2', '78m²', '119m²', 'Family Mart (2 min)']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_c5b71c57-6225-11f1-bd67-a6ae20f6eefe_b4565d74d6aa7.jpg', 'Meguro, Tokyo', '$1,750,000', 'House, Apartment, Land', '4', '148m²', '137m²', 'Lawson (3 min)']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_9cefe654-6225-11f1-bd67-a6ae20f6eefe_e7a7978b6de5d.jpg', 'Meguro, Tokyo', '$1,930,000', 'House', '1', '130m²', '146m²', 'Seven Eleven (2 min)']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_8bd47437-6225-11f1-bd67-a6ae20f6eefe_df8e5dffdf1e6.jpg', 'Meguro, Tokyo', '$2,120,000', 'House', '3', '77m²', '88m²', 'Seven Eleven (2 min)']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_6d006b79-6225-11f1-bd67-a6ae20f6eefe_c6fc5d107f38c.jpg', 'Meguro, Tokyo', '$3,750,000', 'House, Apartment, Land', '4', '188m²', '194m²', 'Sunkus (5 min)']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_59f245fd-6225-11f1-bd67-a6ae20f6eefe_a84a2ffd41f76.jpg', 'Meguro, Tokyo', '$5,020,000', 'House, Apartment, Land', '7', '264m²', '361m²', 'Seven Eleven (5 min)']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_49384353-6225-11f1-bd67-a6ae20f6eefe_f67f2fb2597df.jpg', 'Meguro, Tokyo', '$550,000', 'House, Apartment, Land', '3', '63m²', '87m²', 'Seven Eleven (2 min)']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_12e8d80d-6225-11f1-bd67-a6ae20f6eefe_da3756fe532fe.jpg', 'Meguro, Tokyo', '$810,000', 'House', '3', '165m²', '96m²', 'Seven Eleven (4 min)']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_05662c34-6225-11f1-bd67-a6ae20f6eefe_260d80702775e.jpg', 'Meguro, Tokyo', '$990,000', 'House, Land', '4', '166m²', '129m²', 'Family Mart (4 min)']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_eb2f8df1-6224-11f1-bd67-a6ae20f6eefe_ef22a0d49f49d.jpg', 'Meguro, Tokyo', '$1,060,000', 'House, Apartment, Land', '2', '90m²', '129m²', 'Family Mart (4 min)']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/fp/fp_cfdf9c33-6224-11f1-bd67-a6ae20f6eefe_4ffb343a9cef9.jpg', 'Tsuzuki, Kanagawa', '$490,000', 'Land', '-', '239m²', '-', 'Mini Stop (3 min)']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/fp/fp_c716447f-6224-11f1-bd67-a6ae20f6eefe_46fa47ff8937a.jpg', 'Tsuzuki, Kanagawa', '$850,000', 'Land', '-', '410m²', '-', 'Seven Eleven (3 min)']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/fp/fp_bf5f7f9a-6224-11f1-bd67-a6ae20f6eefe_02a2300bd0bfc.jpg', 'Tsuzuki, Kanagawa', '$140,000', 'Land', '-', '64m²', '-', 'Seven Eleven (8 min)']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/fp/fp_9bbdb566-6224-11f1-bd67-a6ae20f6eefe_929a0841f4e67.jpg', 'Tsuzuki, Kanagawa', '$590,000', 'Land', '-', '210m²', '-', 'Sunkus (4 min)']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_902c3978-6224-11f1-bd67-a6ae20f6eefe_cd8b28dd3b1ae.jpg', 'Meguro, Tokyo', '$1,240,000', 'House, Apartment, Land', '3', '62m²', '103m²', 'Seven Eleven (4 min)']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/fp/fp_810872c6-6224-11f1-bd67-a6ae20f6eefe_f56ca1b6620ba.jpg', 'Tsuzuki, Kanagawa', '$870,000', 'Land', '-', '260m²', '-', 'Family Mart (3 min)']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/fp/fp_6353471f-6224-11f1-bd67-a6ae20f6eefe_00d71cb43bbca.jpg', 'Tsuzuki, Kanagawa', '$600,000', 'Land', '-', '231m²', '-', 'Seven Eleven (6 min)']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_5a38a10c-6224-11f1-bd67-a6ae20f6eefe_2b52848f0119d.jpg', 'Meguro, Tokyo', '$2,660,000', 'House, Apartment, Land', '3', '145m²', '177m²', 'Family Mart (2 min)']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_46f8bbef-6224-11f1-bd67-a6ae20f6eefe_47806bf5b55b5.jpg', 'Meguro, Tokyo', '$250,000', 'House', '2', '39m²', '53m²', 'Lawson (3 min)']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_343ad094-6224-11f1-bd67-a6ae20f6eefe_9d45948e6ccb2.jpg', 'Meguro, Tokyo', '$250,000', 'House, Apartment, Land', '2', '60m²', '38m²', 'Family Mart (1 min)']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_e11fd8f1-6223-11f1-bd67-a6ae20f6eefe_2a919d2983a0b.jpg', 'Meguro, Tokyo', '$490,000', 'House, Apartment, Land', '3', '88m²', '95m²', 'Family Mart (1 min)']
['https://akiyajapan.sgp1.cdn.digitaloceanspaces.com/storage/property/sp/sp_d3747754-6223-11f1-bd67-a6ae20f6eefe_49fadc07255eb.jpg', 'Meguro, Tokyo', '$510,000', 'House', '3', '53m²', '59m²', 'Mini Stop (3 min)']

In [45]:
df = pd.DataFrame(akiya)

In [46]:
file_exists = os.path.isfile('akiya_data.csv')
df.to_csv('akiya_data.csv', mode='a', index=False, header=not file_exists)

In [47]:
fd = pd.read_csv('akiya_data.csv')
fd

,Image,Location,Price,Type,Beds,Land,House,Konbini
0,https://akiyajapan.sgp1.cdn.digitaloceanspaces...,"Aoba, Kanagawa","$340,000","Apartment, Land",3,-,72m²,Lawson (4 min)
1,https://akiyajapan.sgp1.cdn.digitaloceanspaces...,"Seiyo, Ehime","$19,000","House, Land",2,221m²,84m²,Sunkus (36 min)
2,https://akiyajapan.sgp1.cdn.digitaloceanspaces...,"Shinagawa, Tokyo","$1,560,000","House, Apartment, Land",3,91m²,141m²,Seven Eleven (2 min)
3,https://akiyajapan.sgp1.cdn.digitaloceanspaces...,"Bungo Ono, Oita","$25,000",House,9,632m²,158m²,Family Mart (18 min)
4,https://akiyajapan.sgp1.cdn.digitaloceanspaces...,"Shinagawa, Tokyo","$1,820,000","House, Apartment, Land",4,137m²,212m²,Sunkus (1 min)
...,...,...,...,...,...,...,...,...
85,https://akiyajapan.sgp1.cdn.digitaloceanspaces...,"Meguro, Tokyo","$2,660,000","House, Apartment, Land",3,145m²,177m²,Family Mart (2 min)
86,https://akiyajapan.sgp1.cdn.digitaloceanspaces...,"Meguro, Tokyo","$250,000",House,2,39m²,53m²,Lawson (3 min)
87,https://akiyajapan.sgp1.cdn.digitaloceanspaces...,"Meguro, Tokyo","$250,000","House, Apartment, Land",2,60m²,38m²,Family Mart (1 min)
88,https://akiyajapan.sgp1.cdn.digitaloceanspaces...,"Meguro, Tokyo","$490,000","House, Apartment, Land",3,88m²,95m²,Family Mart (1 min)
89,https://akiyajapan.sgp1.cdn.digitaloceanspaces...,"Meguro, Tokyo","$510,000",House,3,53m²,59m²,Mini Stop (3 min)